### ISSUE TITLE
can't install on windows

### ISSUE THREAD

**Issue by Akudrevatykh** [atom/grunt-electron-installer#12]
calling npm install grunt-atom-shell-installer --save-dev
Windows 8.1

```
nstaller\node_modules\asar\node_modules\chromium-pickle
> node-gyp rebuild


E:\Projects\test\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chromium-pickle>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at exports._errnoException (util.js:742:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1028:32)
gyp ERR! stack     at child_process.js:1109:20
gyp ERR! stack     at process._tickCallback (node.js:343:11)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Projects\test\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chromium-pickle
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! chromium-pickle@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromium-pickle@0.1.4 install script.
npm ERR! This is most likely a problem with the chromium-pickle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromium-pickle
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-atom-shell-installer" "--save-dev"
npm ERR! cwd E:\Projects\test
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9


npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\Projects\test\npm-debug.log
npm ERR! not ok code 0
```

full log http://www.filedropper.com/npm-debug

**Comment by ummo** [comment]
same error

**Comment by catgirl666** [comment]
Where need write this "npm install grunt-atom-shell-installer"? I no see installing shell in my Atom's menu.

**Comment by paulcbetts** [comment]
You probably need to use node 0.10.x
