### ISSUE TITLE
Getting outofmemoryexception seemingly randomly after install finishes

### ISSUE THREAD

**Issue by maxkorp** [atom/grunt-electron-installer#25]
So the error happens whenthe installer is still running, but it's finished copying files, and throws up the "there's been an error" type message popup. Checking the log gives
```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\someuser\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\someuser\AppData\Local\gitkraken\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\someuser\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\someuser\AppData\Local\gitkraken\app-0.0.1
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\someuser\AppData\Local\gitkraken\app-0.0.1\GitKraken.exe]
ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\someuser\AppData\Local\gitkraken\app-0.0.1\GitKraken.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClassf.<InvokeProcessAsync>b__e()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb5.<<invokePostInstall>b__a9>d__b7.MoveNext()
ApplyReleasesImpl: Starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: cleanDeadVersions: for version 0.0.1
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.1
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\someuser\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\someuser\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\someuser\AppData\Local\gitkraken\app-0.0.1\GitKraken.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\someuser\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\someuser\AppData\Local\gitkraken\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\someuser\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\someuser\AppData\Local\gitkraken\app-0.0.2
IEnableLogger: Failed to install package to app dir: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at NuGet.StreamExtensions.ToStreamFactory(Stream stream)
   at NuGet.ZipPackageFile..ctor(PackagePart part)
   at NuGet.ZipPackage.<GetFilesNoCache>b__12(PackagePart part)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.ZipPackage.GetFilesNoCache()
   at NuGet.ZipPackage.GetFilesBase()
   at NuGet.LocalPackage.GetFiles()
   at NuGet.PackageExtensions.GetFiles(IPackage package, String directory)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__8e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
 ```

It seems persistent per machine, but different machines with similar ram usage might work or not work. Has anybody seen this before?

**Comment by maxkorp** [comment]
Totally forgot I had this logged.
The root of the issue is here: https://github.com/Squirrel/Squirrel.Windows/issues/309#issuecomment-113079905

The "after finishing" is actually because it was running once to do install and the second time to run the app, and i hadn't picked up on squirrel events yet and it was just running the app.

**Comment by kevinsawicki** [comment]
Closing this out since it is a core squirrel for windows update and this package is regularly updated when new squirrel versions are released so a new version of this package will be published once a fix is available.
