### ISSUE TITLE
Error installing in MS Server 2012

### ISSUE THREAD

**Issue by Rameshv** [atom/grunt-electron-installer#31]
Hi,
   I can't install this module on MS 2012 server. I am getting this following error
````
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
69:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\pocketworks\Fresenius-pc\node_modules\grunt-electron-installer\node_modules\asar\node_modules\chromium-p
ickle
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
```

Is this anyway related to dotnet version..??

**Comment by bzuillsmith** [comment]
Definitely sounds like it. What versions of .NET do you have installed on the MS 2012 server?

**Comment by Rameshv** [comment]
Its 4.0 @bzuillsmith

**Comment by bzuillsmith** [comment]
Right, but do you have .net 3.5 Installed?

**Comment by Rameshv** [comment]
Sorry @bzuillsmith for the late reply.. Initially I dont have .net 3.5. But installed just then, still getting the  error. But this is bit different

````
C:\pocketworks\Fresenius-pc\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chromium-pickle\node
_modules\native-mate\vendor\base-minimal\src\base/atomicops_internals_x86_msvc.h(10): fatal error C1083: Cannot open in
clude file: 'WinSock2.h': No such file or directory [C:\pocketworks\Fresenius-pc\node_modules\grunt-atom-shell-installe
r\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\native_mate.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
69:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\pocketworks\Fresenius-pc\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chromium
-pickle
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
" "-S" "grunt-atom-shell-installer" "--msvs_version=2010"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1

**Comment by paulcbetts** [comment]
The latest version of ASAR doesn't need native code, so this should be :gem:
