### ISSUE TITLE
"System.IO.IOException: Process cannot access the file" during build.

### ISSUE THREAD

**Issue by gbmhunter** [atom/grunt-electron-installer#54]
Upon running "grunt create-windows-installer" I get the following error:

```
Running "create-windows-installer:x64" (create-windows-installer) task
>> System.IO.IOException: The process cannot access the file 'C:\temp\output\Nin
jaTerm.0.1.0.nupkg' because it is being used by another process.
>>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>>    at System.IO.File.InternalDelete(String path, Boolean checkHost)
>>    at System.IO.File.Delete(String path)
>>    at Squirrel.Update.Program.Releasify(String package, String targetDir, Str
ing packagesDir, String bootstrapperExe, String backgroundGif, String signingOpt
s, String baseUrl, String setupIcon)
>>    at Squirrel.Update.Program.executeCommandLine(String[] args)
>>    at Squirrel.Update.Program.main(String[] args)
>>    at Squirrel.Update.Program.Main(String[] args)
```

I have made sure the output directory is not in any cloud-syncing folder, and even run the command-line in administrator mode but no luck. I have tried putting the output file somewhere completely different on my computer but that didn't work either.

I am running Windows 8 64-bit.

**Comment by gbmhunter** [comment]
Sorry, duplicate of #53.
