### ISSUE TITLE
can't install on windows

### ISSUE THREAD

**Issue by luisrudge** [atom/grunt-electron-installer#9]
first I had a problem with python 3.4.2. I removed that version and installed 2.7.9.
But now I'm having this error:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB 8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build usi ng the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrad e to the current Visual Studio tools by selecting the Project menu or right-click the solution, and th en selecting "Upgrade Solution...". [c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installe r\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\vendor\base-minimal\base.vcx proj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB 8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build usi ng the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrad e to the current Visual Studio tools by selecting the Project menu or right-click the solution, and th en selecting "Upgrade Solution...". [c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installe r\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\native_mate.vcxproj]

**Comment by paulcbetts** [comment]
Do you have >1 version of VS installed? You might have to set an Environment Variable `GYP_USE_MSVS=2013` to fix this

**Comment by luisrudge** [comment]
I have vs shell 2010 because of sql express. I'll try the ENV.

**Comment by luisrudge** [comment]
Nope. :(

```
c:\git\gh\hello-atom\build (master)
λ %GYP_USE_MSVS%
'2013' is not recognized as an internal or external command,
operable program or batch file.

c:\git\gh\hello-atom\build (master)
λ echo %GYP_USE_MSVS%
2013

c:\git\gh\hello-atom\build (master)
λ npm i -S grunt-atom-shell-installer
npm WARN package.json hello-atom-build@0.1.0 No description
npm WARN package.json hello-atom-build@0.1.0 No repository field.
npm WARN package.json hello-atom-build@0.1.0 No README data
/


> native-mate@0.2.6 install c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installer\node_mod
ules\asar\node_modules\chromium-pickle\node_modules\native-mate
> echo

ECHO is on.



> chromium-pickle@0.1.4 install c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installer\node
_modules\asar\node_modules\chromium-pickle
> node-gyp rebuild


c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chrom
ium-pickle {git}
{lamb} node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
\node-gyp.js" rebuild
Warning: Missing input files:
c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chrom
ium-pickle\node_modules\native-mate\tests\compilation.cc
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" swi
tch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB
8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build usi
ng the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrad
e to the current Visual Studio tools by selecting the Project menu or right-click the solution, and th
en selecting "Upgrade Solution...". [c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installe
r\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\vendor\base-minimal\base.vcx
proj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB
8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build usi
ng the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrad
e to the current Visual Studio tools by selecting the Project menu or right-click the solution, and th
en selecting "Upgrade Solution...". [c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installe
r\node_modules\asar\node_modules\chromium-pickle\node_modules\native-mate\native_mate.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-g
yp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\nod
e-gyp.js" "rebuild"
gyp ERR! cwd c:\git\gh\hello-atom\build\node_modules\grunt-atom-shell-installer\node_modules\asar\node_
modules\chromium-pickle
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! chromium-pickle@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromium-pickle@0.1.4 install script.
npm ERR! This is most likely a problem with the chromium-pickle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromium-pickle
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "i" "-S" "grunt-atom-shell-installer"
npm ERR! cwd c:\git\gh\hello-atom\build
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by paulcbetts** [comment]
Try http://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012

**Comment by luisrudge** [comment]
Damnn! That worked. Thanks!

`npm i -S grunt-atom-shell-installer --msvs_version=2013`

**Comment by sethlivingston** [comment]
Got this from Avast! when I ran this comment. Is this a false positive?

![image](https://cloud.githubusercontent.com/assets/574793/6877339/34fef9e2-d49e-11e4-883d-07a026839cb1.png)

**Comment by paulcbetts** [comment]
It's definitely a false positive, you can build this EXE yourself if you're not confident though: github.com/squirrel/squirrel.windows

**Comment by kevinsawicki** [comment]
Closing this out, appears to have been a Visual Studio detection issue fixed by explicitly setting `--msvs_version=` to `npm install`.
