### ISSUE TITLE
Unhandled exception: System.AggregateException: One or more errors occurred.

### ISSUE THREAD

**Issue by nnasoody** [atom/grunt-electron-installer#92]
I am using grunt-electron-installer version 1.2.0 to build the windows installer (on a windows platform). The rcedit.exe executable seems to be tripping up and I'm not sure how to go about resolving this issue. Here's part of the output from the SquirrelSetup.log in the vendor folder: 

```
Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to modify resources, command invoked was: 'c:\project_name\discovery\node_modules\grunt-electron-installer\vendor\rcedit.exe "c:\project_name\discovery\installer\Setup.exe" --set-version-string "CompanyName" "MyName" --set-version-string "LegalCopyright" "Copyright © 2015 MyName" --set-version-string "FileDescription" "project-description" --set-version-string "ProductName" "project-description" --set-file-version 1.0.0 --set-product-version 1.0.0'

Output was:
   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__a2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass78.<Releasify>b__72()
   at Squirrel.Utility.<>c__DisplayClassc.<Retry>b__b()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to modify resources, command invoked was: 'c:\project_name\discovery\node_modules\grunt-electron-installer\vendor\rcedit.exe "c:\project_name\discovery\installer\Setup.exe" --set-version-string "CompanyName" "MyName" --set-version-string "LegalCopyright" "Copyright © 2015 MyName" --set-version-string "FileDescription" "project-description" --set-version-string "ProductName" "project-description" --set-file-version 1.0.0 --set-product-version 1.0.0'
```

Any ideas?

**Comment by nnasoody** [comment]
This problem is resolved. 

I ran the following command on its own:

```
'c:\project_name\discovery\node_modules\grunt-electron-installer\vendor\rcedit.exe "c:\project_name\discovery\installer\Setup.exe" --set-version-string "CompanyName" "MyName" --set-version-string "LegalCopyright" "Copyright © 2015 MyName" --set-version-string "FileDescription" "project-description" --set-version-string "ProductName" "project-description" --set-file-version 1.0.0 --set-product-version 1.0.0'
```

And the error message complained about vspc100.dll missing. To resolve this, I downloaded and installed the c++ redistributable 2010. 

Grunt-electron-installer works as expected and there was no issue with it.
